# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bane"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Wellman"]
  s.date = "2012-08-18"
  s.description = "    Bane is a test harness used to test your application's interaction with\n    other servers. It is based upon the material from Michael Nygard's \"Release\n    It!\" book as described in the \"Test Harness\" chapter.\n"
  s.email = "dan@danielwellman.com"
  s.executables = ["bane"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "TODO"
  ]
  s.files = [
    "Rakefile",
    "bin/bane",
    "examples/multiple_behaviors.rb",
    "examples/readme_example.rb",
    "examples/single_behavior.rb",
    "lib/bane.rb",
    "lib/bane/behavior_server.rb",
    "lib/bane/behaviors.rb",
    "lib/bane/command_line_configuration.rb",
    "lib/bane/compatibility.rb",
    "lib/bane/configuration_parser.rb",
    "lib/bane/launcher.rb",
    "lib/bane/naive_http_response.rb",
    "lib/bane/service_registry.rb",
    "test/bane/behavior_server_test.rb",
    "test/bane/behaviors_test.rb",
    "test/bane/command_line_configuration_test.rb",
    "test/bane/configuration_parser_test.rb",
    "test/bane/fake_connection_test.rb",
    "test/bane/integration_test.rb",
    "test/bane/naive_http_response_test.rb",
    "test/bane/service_registry_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/danielwellman/bane"
  s.licenses = ["BSD"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A test harness for socket connections based upon ideas from Michael Nygard's 'Release It!'"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
  end
end

