# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bane 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "bane"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Daniel Wellman", "Joe Leo"]
  s.date = "2014-06-21"
  s.description = "    Bane is a test harness used to test your application's interaction with\n    other servers. It is based upon the material from Michael Nygard's \"Release\n    It!\" book as described in the \"Test Harness\" chapter.\n"
  s.email = "dan@danielwellman.com"
  s.executables = ["bane"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "TODO"
  ]
  s.files = [
    "Rakefile",
    "bin/bane",
    "examples/multiple_behaviors.rb",
    "examples/readme_example.rb",
    "examples/single_behavior.rb",
    "lib/bane.rb",
    "lib/bane/arguments_parser.rb",
    "lib/bane/behavior_maker.rb",
    "lib/bane/behaviors/responders/close_after_pause.rb",
    "lib/bane/behaviors/responders/close_immediately.rb",
    "lib/bane/behaviors/responders/deluge_response.rb",
    "lib/bane/behaviors/responders/echo_response.rb",
    "lib/bane/behaviors/responders/exported.rb",
    "lib/bane/behaviors/responders/fixed_response.rb",
    "lib/bane/behaviors/responders/for_each_line.rb",
    "lib/bane/behaviors/responders/http_refuse_all_credentials.rb",
    "lib/bane/behaviors/responders/never_respond.rb",
    "lib/bane/behaviors/responders/newline_response.rb",
    "lib/bane/behaviors/responders/random_response.rb",
    "lib/bane/behaviors/responders/slow_response.rb",
    "lib/bane/behaviors/servers/exported.rb",
    "lib/bane/behaviors/servers/responder_server.rb",
    "lib/bane/behaviors/servers/timeout_in_listen_queue.rb",
    "lib/bane/command_line_configuration.rb",
    "lib/bane/extensions.rb",
    "lib/bane/launcher.rb",
    "lib/bane/naive_http_response.rb",
    "test/bane/acceptance_test.rb",
    "test/bane/arguments_parser_test.rb",
    "test/bane/bane_test.rb",
    "test/bane/behaviors/responders/close_after_pause_test.rb",
    "test/bane/behaviors/responders/close_immediately_test.rb",
    "test/bane/behaviors/responders/deluge_response_test.rb",
    "test/bane/behaviors/responders/echo_response_test.rb",
    "test/bane/behaviors/responders/fixed_response_test.rb",
    "test/bane/behaviors/responders/for_each_line_test.rb",
    "test/bane/behaviors/responders/http_refuse_all_credentials_test.rb",
    "test/bane/behaviors/responders/never_respond_test.rb",
    "test/bane/behaviors/responders/newline_response_test.rb",
    "test/bane/behaviors/responders/random_response_test.rb",
    "test/bane/behaviors/responders/slow_response_test.rb",
    "test/bane/behaviors/servers/responder_server_test.rb",
    "test/bane/behaviors/servers/timeout_in_listen_queue_test.rb",
    "test/bane/command_line_configuration_test.rb",
    "test/bane/extensions_test.rb",
    "test/bane/fake_connection_test.rb",
    "test/bane/launchable_role_tests.rb",
    "test/bane/naive_http_response_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/danielwellman/bane"
  s.licenses = ["BSD"]
  s.rubygems_version = "2.2.2"
  s.summary = "A test harness for socket connections based upon ideas from Michael Nygard's 'Release It!'"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.5"])
      s.add_development_dependency(%q<jeweler>, ["= 2.0.1"])
      s.add_development_dependency(%q<test-unit>, ["= 1.2.3"])
      s.add_development_dependency(%q<mocha>, [">= 0.14.0"])
      s.add_development_dependency(%q<wwtd>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.1.5"])
      s.add_dependency(%q<jeweler>, ["= 2.0.1"])
      s.add_dependency(%q<test-unit>, ["= 1.2.3"])
      s.add_dependency(%q<mocha>, [">= 0.14.0"])
      s.add_dependency(%q<wwtd>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.1.5"])
    s.add_dependency(%q<jeweler>, ["= 2.0.1"])
    s.add_dependency(%q<test-unit>, ["= 1.2.3"])
    s.add_dependency(%q<mocha>, [">= 0.14.0"])
    s.add_dependency(%q<wwtd>, [">= 0"])
  end
end

