require 'bane/extensions'
require 'bane/service_maker'
require 'bane/behaviors'
require 'bane/services'
require 'bane/launcher'
require 'bane/behavior_server'
require 'bane/arguments_parser'
require 'bane/naive_http_response'
